INSERT INTO achievements (id, title, description, category, icon, color, requirement_type, requirement_count, xp_reward, coin_reward, is_secret) VALUES
  ('first-steps', 'First Steps', 'Complete your first lesson.', 'learning', 'Footprints', '#22c55e', 'lessons_completed', 1, 10, 10, false),
  ('getting-warm', 'Getting Warm', 'Complete 5 lessons.', 'learning', 'Flame', '#f97316', 'lessons_completed', 5, 25, 15, false),
  ('lesson-learner', 'Lesson Learner', 'Complete 25 lessons.', 'learning', 'BookOpen', '#3b82f6', 'lessons_completed', 25, 50, 25, false),
  ('quiz-whiz', 'Quiz Whiz', 'Complete your first quiz.', 'learning', 'HelpCircle', '#8b5cf6', 'quizzes_completed', 1, 15, 10, false),
  ('perfect-score', 'Perfect Score', 'Score 100% on any quiz.', 'learning', 'Target', '#eab308', 'perfect_quiz', 1, 50, 25, false),
  ('night-owl', 'Night Owl', 'Complete a lesson between midnight and 4am.', 'learning', 'Moon', '#6366f1', 'night_lesson', 1, 25, 15, true),
  ('course-starter', 'Course Starter', 'Enroll in your first course.', 'learning', 'Rocket', '#ec4899', 'course_enrolled', 1, 10, 10, false),
  ('course-finisher', 'Course Finisher', 'Complete your first course.', 'learning', 'Trophy', '#f59e0b', 'course_completed', 1, 100, 50, false),
  ('hello-world', 'Hello World', 'Submit your first code solution.', 'coding', 'Terminal', '#22c55e', 'challenges_solved', 1, 15, 10, false),
  ('bug-hunter', 'Bug Hunter', 'Solve 5 challenges.', 'coding', 'Bug', '#ef4444', 'challenges_solved', 5, 50, 25, false),
  ('code-newbie', 'Code Newbie', 'Solve 10 challenges.', 'coding', 'Code', '#3b82f6', 'challenges_solved', 10, 75, 40, false),
  ('first-try-hero', 'First Try Hero', 'Solve 5 challenges on the first attempt.', 'coding', 'Zap', '#eab308', 'first_try_solves', 5, 100, 50, false),
  ('speed-coder', 'Speed Coder', 'Solve a challenge in under 2 minutes.', 'coding', 'Timer', '#f97316', 'fast_solve', 1, 50, 25, false),
  ('polyglot', 'Polyglot', 'Code in 3 different languages.', 'coding', 'Languages', '#8b5cf6', 'languages_used', 3, 150, 75, false),
  ('first-day', 'First Day', 'Complete your first daily activity.', 'streak', 'Sun', '#f59e0b', 'streak_days', 1, 10, 10, false),
  ('three-day-streak', '3-Day Streak', 'Maintain a 3-day streak.', 'streak', 'Flame', '#f97316', 'streak_days', 3, 25, 15, false),
  ('week-warrior', 'Week Warrior', 'Maintain a 7-day streak.', 'streak', 'Flame', '#ef4444', 'streak_days', 7, 50, 25, false),
  ('monthly-master', 'Monthly Master', 'Maintain a 30-day streak.', 'streak', 'Crown', '#eab308', 'streak_days', 30, 200, 100, false),
  ('unstoppable', 'Unstoppable', 'Maintain a 100-day streak.', 'streak', 'Crown', '#6366f1', 'streak_days', 100, 500, 250, false),
  ('top-100', 'Top 100', 'Reach top 100 on the leaderboard.', 'social', 'TrendingUp', '#22c55e', 'leaderboard_rank', 100, 100, 50, false),
  ('rising-star', 'Rising Star', 'Gain 500 XP in a single day.', 'social', 'Star', '#eab308', 'xp_single_day', 500, 75, 40, false),
  ('bitzy-pioneer', 'Bitzy Pioneer', 'Join during the launch period.', 'special', 'Rocket', '#ec4899', 'join_date', 1, 50, 50, false),
  ('profile-perfectionist', 'Profile Perfectionist', 'Complete 100% of your profile.', 'special', 'UserCheck', '#3b82f6', 'profile_complete', 1, 25, 15, false),
  ('quest-complete', 'Quest Complete', 'Complete 10 daily quests.', 'special', 'Scroll', '#8b5cf6', 'quests_completed', 10, 50, 25, false),
  ('rich', 'Rich', 'Accumulate 1000 coins.', 'special', 'Coins', '#eab308', 'coins_accumulated', 1000, 50, 0, true),
  ('konami-code', 'Konami Code', 'You found a secret!', 'secret', 'Gamepad2', '#6366f1', 'easter_egg', 1, 100, 50, true),
  ('html-rookie', 'HTML Rookie', 'Complete the HTML Fundamentals course.', 'course', 'FileCode', '#e34c26', 'course_completed', 1, 100, 50, false),
  ('css-artist', 'CSS Artist', 'Complete the CSS Fundamentals course.', 'course', 'Palette', '#264de4', 'course_completed', 1, 100, 50, false),
  ('js-ninja', 'JS Ninja', 'Complete the JavaScript Basics course.', 'course', 'Braces', '#f7df1e', 'course_completed', 1, 150, 75, false),
  ('react-champion', 'React Champion', 'Complete the React Fundamentals course.', 'course', 'Atom', '#61dafb', 'course_completed', 1, 200, 100, false),
  ('python-wizard', 'Python Wizard', 'Complete the Python Fundamentals course.', 'course', 'Terminal', '#3776ab', 'course_completed', 1, 150, 75, false),
  ('computer-fundamentals-badge', 'Digital Foundation', 'Complete the Computer Fundamentals course.', 'course', 'Cpu', '#64748b', 'course_completed', 1, 100, 50, false),
  ('c-programmer', 'C Programmer', 'Complete the C course.', 'course', 'Hash', '#5c6bc0', 'course_completed', 1, 150, 75, false),
  ('cpp-master', 'C++ Master', 'Complete the C++ course.', 'course', 'Layers', '#00599c', 'course_completed', 1, 175, 85, false),
  ('java-developer', 'Java Developer', 'Complete the Java course.', 'course', 'Coffee', '#e76f00', 'course_completed', 1, 175, 85, false)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  requirement_type = EXCLUDED.requirement_type,
  requirement_count = EXCLUDED.requirement_count,
  xp_reward = EXCLUDED.xp_reward,
  coin_reward = EXCLUDED.coin_reward,
  is_secret = EXCLUDED.is_secret;
